id = "hydeproject"
owner = "The HyDE Project"
version = "0.1.0"
# dots = ["hyde", "waybar", "dunst", "kitty", "rofi", "nvidia"]
dots = ["hyde"]
default_action = "preserve"
user_home = "${HOME}"
package_manager = ["pacman", "yay", "flatpak"]          # "auto" | "pacman" | "dnf"
repository = "https://github.com/HyDE-Project/HyDE.git" # Only supports single repo
start_command = ["echo 'Starting Deez-Dots for HydE'"]
end_command = ["echo 'Command ends'"]

[dependency]
'yay,paru' = ["hyde-cli-git"]
flatpak = ["dev.vencord.Vesktop"]
pacman = [
    "hyprland",
    "pipewire",
    "pipewire-pulse",
    "pipewire-jack",
    "pipewire-alsa",
    "gst-plugin-pipewire",
    "wireplumber",
    "pavucontrol",
]
dnf = ["another-dependency"]

[hyde]
action = "preserve"                             # "preserve" | "overwrite" | "sync" // If child action is not defined use parent action
pre_command = ["echo 'Pre commands for HyDE' "]
post_command = ["echo 'post cmds'"]

[hyde.dependency]
pacman = ["hyprland", "nwg-look", "qt5ct", "qt6ct"]
dnf = ["another-dependency"]

[[hyde.files]]
source_root = "Configs/.config"
target_root = "$XDG_CONFIG_HOME"
paths = [
    "hyde/wallbash",
    "hypr/hyprland.conf",
    "hypr/windowrules.conf",
    "hypr/keybindings.conf",
    "hypr/monitors.conf",
    "hypr/animations.conf",
    "hypr/themes",
]

[[hyde.files]]
source_root = "Configs/.config"
target_root = "${XDG_CONFIG_HOME}"
paths = ["gtk-3.0", "Kvantum", "nwg-look", "qt5ct", "qt6ct", "xsettingsd"]

[[hyde.files]]
source_root = "Configs"
target_root = "${HOME}"
paths = ".gtkrc-2.0"

[[hyde.files]]
action = "overwrite"
source_root = "Configs"
target_root = "${HOME}"
paths = [".local/lib/hyde", "${XDG_DATA_HOME}/hyde"]

[[hyde.files]]
action = "sync"
source_root = "Configs/.local/share"
target_root = "${XDG_DATA_HOME}"
paths = ["icons/Wallbash-Icon", "themes/Wallbash-Gtk"]

[waybar]
pre_command = ["echo 'Pre commands '"]
post_command = ["echo 'HyDE backed up!'"]

[waybar.dependency]
pacman = ["waybar"]

[[waybar.files]]
target_root = "${XDG_CONFIG_HOME}/waybar"
paths = ["config.ctl", "modules", "config.jsonc", "theme.css", "style.css"]

[dunst]
pre_command = ["echo 'Pre commands '"]
post_command = ["echo 'HyDE backed up!'"]


[dunst.dependency]
pacman = ["dunst"]


[[dunst.files]]
source_root = "dunst"
target_root = "${XDG_CONFIG_HOME}"
paths = "dunst"

[[dunst.files]]
action = "overwrite"
target_root = "${HOME}.local/lib"
paths = "hyde/wallbash.dunst.sh"

[kitty]
pre_command = ["echo 'Pre commands '"]
post_command = ["echo 'HyDE backed up!'"]

[kitty.dependency]
pacman = ["kitty"] # dependency

[[kitty.files]]
source_root = "kitty"
target_root = "${XDG_CONFIG_HOME}"
paths = "kitty"

[[kitty.files]]
action = "overwrite"
source_root = "kitty/hyde/wallbash/scripts"
target_root = "${XDG_CONFIG_HOME}/hyde/wallbash/scripts"
paths = "kitty.sh"


#  nvidia.conf is separate because it has a different dependency
[nvidia]
pre_command = "echo 'Pre commands '"    # Pre commands
post_command = "echo 'HyDE backed up!'" # Post commands


[[nvidia.files]]
action = "preserve"
source_root = "nvidia"
target_root = "${XDG_CONFIG_HOME}/hypr"
paths = "nvidia.conf"

[nvidia.dependency]
pacman = ["nvidia-utils", "nvidia"]
dnf = ["another-dependency"]


[rofi]
action = "preserve"                     # "preserve" | "overwrite" | "sync" // If child action is not defined use parent action
pre_command = "echo 'Pre commands '"    # Pre commands
post_command = "echo 'HyDE backed up!'" # Post commands

[rofi.dependency]
pacman = ["rofi"] # dependency

[[rofi.files]]
source_root = "rofi"
target_root = "${XDG_CONFIG_HOME}"
